_target_: src.models.CNN2d
_recursive_: False
n_classes: 10
channels: [100, 100, 100]
local_kernel_size: 6
hidden_dims: [1600, 100]
padding: 3
bias: True
batchnorm: True
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001