_target_: src.models.InvariantCNN
_recursive_: False
n_classes: 10
channels: [64, 64, 10]
local_kernel_size: 3
hidden_dims: [160, 100]
padding: 1
bias: True
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001