_target_: src.models.LCN1d
_recursive_: False
n_classes: 10
in_channels: 64
channels: [128, 128, 128]
local_kernel_size: 3
in_widths: [64, 32, 16]
hidden_dims: [1024, 100]
stride: 1
pool_kernel_size: 2
padding: 1
bias: True
batchnorm: True
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001