_target_: src.models.LCN2d
_recursive_: False
n_classes: 10
channels: [100, 100, 100]
local_kernel_size: 3
in_heights: [32, 16, 8]
in_widths: [32, 16, 8]
hidden_dims: [1600, 100]
stride: 1
pool_kernel_size: 2
padding: 1
bias: True
batchnorm: True
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001