defaults:
  - model_cfg: LCN2d_same_weights
  - data_cfg: CIFAR10
  - loggers@trainer_cfg: Default
  - callbacks@trainer_cfg: Default
  - override hydra/launcher: submitit_slurm
  #- override hydra/sweeper: ax
  - _self_

experiment_id: test_lcn_cifar_same_weights
ckpt_path: ${hydra:runtime.cwd}/results/train/train_lcn_cifar_same_weights/2021-12-08/14-10-01/logs/default/version_0/checkpoints/checkpoint_epoch=45.ckpt

hydra:
  run:
    dir: ./results/test/${experiment_id}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: ${hydra.run.dir}

  launcher:
    partition: gaia
    nodes: ${trainer_cfg.num_nodes}
    tasks_per_node: ${trainer_cfg.gpus}
    constraint: xeon-g6
    timeout_min: 1000000
    additional_parameters:
      gres: gpu:volta:2
      exclusive: True

trainer_cfg:
  _target_: pytorch_lightning.Trainer
  num_nodes: 1
  gpus: 1
  strategy: ddp
  precision: 16
  max_epochs: 1000

data_cfg:
  datamodule:
    num_workers: 20